### ISSUE TITLE
对比试验表格

### ISSUE THREAD

**Issue by ElliottZhen** [Tchuanm/SFTransT#10]
![image](https://github.com/Tchuanm/SFTransT/assets/56305119/867be8fa-7874-4d21-a0c4-0ac993a474fa)
你好，请问表格中的这种竖线，如何做到不挨着上下两条横线。我找了很多办法，只有横线断开的办法，竖线没有用。

**Comment by ElliottZhen** [comment]
@Tchuanm

**Comment by Tchuanm** [comment]
你可以在arxiv 查看论文pdf的latex源代码 查看如何做到
