### ISSUE TITLE
关于代码是否开源

### ISSUE THREAD

**Issue by RelayZ** [Tchuanm/SFTransT#4]
您好，我对您的工作非常感兴趣，请问是否会开源呢？

**Comment by Tchuanm** [comment]
您好，目前还在审稿中、会在中稿之后开源，目前只是Arxiv版本。我们并没有承诺三个月内开源。

**Comment by RelayZ** [comment]
不好意思，我以为您目前是已经中了《IEEE TRANSACTIONS ON CIRCUITS AND SYSTEMS FOR VIDEO TECHNOLOGY 》这个期刊。   我还想问一下，您论文中的GPA模块，依据(x<sub>c</sub> , y<sub>c</sub>) 和 ( $\sigma$<sub>w</sub> , $\sigma$<sub>h</sub>) 生成的G<sub>0</sub><sup>L</sup>维度是什么样的？若搜索区域输入维度是256×256，模板输入维度是128×128。仅依靠搜索区域生成的高斯图G<sub>0</sub><sup>L</sup>的尺寸应当是(B, N, 256, 256)，而与之相加的特征图应该是(B, N, 256, 128)，请问这里是如何相加的呢？
