### ISSUE TITLE
About your baseline

### ISSUE THREAD

**Issue by ElliottZhen** [Tchuanm/SFTransT#6]
你好，请问你们论文中的消融实验表8中的baseline  在您在代码中有吗，我觉得看起来挺简洁，我是一个初学者，想要找一个基线，简单的学习，另外您的baseline训练的大概时间、训练设置和硬件是否方便公开，非常感谢，期待您的回复！

**Comment by Tchuanm** [comment]
表中的baseline 是指将六曾GPHA模块替换成为基本的多头互注意力模块（DETR中的decoder）。  具体的， 可以将`[这行](https://github.com/Tchuanm/SFTransT/blob/main/ltr/models/neck/NeckAug.py#L16)`替换为普通的Transformer模块。 或者在NeckAug.py中删除我们设计的空间-频谱设计行即可。

训练时间来说 大概2-3天， 4*RTX3090. 其他设置在config中都有。
