### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by chenmiao11** [Tchuanm/SFTransT#7]
你好，请问图八怎么可视化的。

**Comment by chenmiao11** [comment]
不同追踪器在lasot上的追踪结果从哪获得的

**Comment by Tchuanm** [comment]
Fig.8 consist of attention spatial map and frequency map. spatial is offered in show_CAM.py.  frequency are directly visiulized the each heat of attention. It's easy to do.

**Comment by Tchuanm** [comment]
The LaSOT results are get from the original papers.
