### ISSUE TITLE
测试的参数

### ISSUE THREAD

**Issue by ElliottZhen** [Tchuanm/SFTransT#8]
你好，我想测试你的代码，我发现了两个问题：
1.pysot_toolkit里边好像没有eval_got10k_global.py这个文件
2.test_global.py这个文件里边的参数我不太清楚，例如win之类的，是测试每个数据集都一样吗，或者我可以从哪里查询到
非常感谢您的回复！

**Comment by Tchuanm** [comment]
1. eval_global.py which consist of  many datasets you can choose.
2. Keep same with our paper.

**Comment by ElliottZhen** [comment]
不好意思打扰您了，非常感谢你的回复，还有一个基础问题想请教您一下，关于加载预训练权重，我看您跳过了att_mask的预训练权重参数，请问swin作为骨干提取特征都是这样的吗，还是说其他原因。谢谢你！

**Comment by Tchuanm** [comment]
refer #9 。
