### ISSUE TITLE
swin transformer pretrain model

### ISSUE THREAD

**Issue by ElliottZhen** [Tchuanm/SFTransT#9]
你好，想向您请教几个问题
1.我发现您加载预训练权重时，跳过了att_mask的预训练权重参数，请问是这样做效果更好吗，还是说其他原因。
2.还有就是swintransformer的v1版本官网没有发现256的与训练模型，请问您提供的是自己训练的吗？
谢谢你！

**Comment by Tchuanm** [comment]
1.  这方面消融我没有做过消融到底哪个好，
2. 我是自己训练的，性能和244差不多我记得。另外V2有提供256的版本，你可以直接用比较方便。
